# @file
# .travis.yml - PKP Plugins Integration

language: php

addons:
  apt:
    update: true

sudo: required

php:
  - 7.2
  - 7.3
  - 7.4
env:
  - APPLICATION=ojs BRANCH=stable-3_2_1 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_2_1 TEST=pgsql

install:
  # Prepare OJS/OMP environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  - cp -r ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/oaiMetadataFormats/oaiJats
  # This plugin also requires the OAI JATS plugin (they are tested together via this script)
  - git clone -b ${BRANCH} https://github.com/pkp/jatsTemplate plugins/generic/jatsTemplate
  # Install OJS/OMP & prep data environment
  - $(npm bin)/cypress run --spec "cypress/tests/data/10-Installation.spec.js,cypress/tests/data/20-CreateContext.spec.js,cypress/tests/data/40-CreateUsers.spec.js,cypress/tests/data/50-CreateIssues.spec.js,cypress/tests/data/50-CreateSections.spec.js,cypress/tests/data/60-content/AmwandengaSubmission.spec.js"
script:
  - $(npm bin)/cypress run --config integrationFolder=plugins/oaiMetadataFormats/oaiJats/cypress/tests
